const ffmpeg = require('fluent-ffmpeg');
const path = require('path');
const fs = require('fs-extra');

/**
 * Metadata Manager - Handles "Raw SEO" for video files
 */

const DEFAULT_TEMPLATES = {
    german_dark_psychology: {
        artist: "Dark Psychology DE",
        album: "Geheimnisse der Manipulation",
        genre: "Education",
        rating: "5",
        comment: "Analytische Psychologie und Verhaltensbeobachtung. #psychologie #manipulation #darkpsychology",
        copyright: "© 2026 Dark Psychology DE"
    },
    default: {
        artist: "SHU Automation",
        album: "Content Factory",
        genre: "Video",
        rating: "5",
        comment: "Generated by SHU Engine",
        copyright: "© 2026 SHU"
    }
};

/**
 * Apply metadata to a video file
 * @param {string} inputPath - Path to source video
 * @param {string} outputPath - Path to saved video
 * @param {Object} metadata - Metadata fields (title, artist, tags, etc.)
 */
async function applyMetadata(inputPath, outputPath, metadata = {}) {
    return new Promise((resolve, reject) => {
        if (!fs.existsSync(inputPath)) {
            return reject(new Error(`Input file not found: ${inputPath}`));
        }

        const template = metadata.template ? (DEFAULT_TEMPLATES[metadata.template] || DEFAULT_TEMPLATES.default) : DEFAULT_TEMPLATES.default;

        const finalMetadata = {
            title: metadata.title || path.basename(inputPath, path.extname(inputPath)),
            artist: metadata.artist || template.artist,
            album: metadata.album || template.album,
            genre: metadata.genre || template.genre,
            comment: metadata.comment || template.comment,
            description: metadata.description || metadata.comment || template.comment,
            copyright: metadata.copyright || template.copyright,
            year: new Date().getFullYear().toString(),
            // Custom rating (FFmpeg metadata key compatibility varies by player)
            rating: metadata.rating || template.rating
        };

        let command = ffmpeg(inputPath)
            .outputOptions('-c copy') // Fast copy, no re-encoding
            .outputOptions('-map_metadata 0'); // Preserve existing metadata

        // Add each metadata field
        Object.keys(finalMetadata).forEach(key => {
            if (finalMetadata[key]) {
                command = command.outputOptions(`-metadata ${key}=${finalMetadata[key]}`);
            }
        });

        // Add tags specifically if provided
        if (metadata.tags) {
            command = command.outputOptions(`-metadata keywords=${metadata.tags}`);
        }

        command
            .on('start', (cmdLine) => console.log(`🚀 [Metadata] Applying SEO thô: ${cmdLine}`))
            .on('end', () => {
                console.log(`✅ [Metadata] Metadata applied successfully to ${outputPath}`);
                resolve(outputPath);
            })
            .on('error', (err) => {
                console.error(`❌ [Metadata] Error: ${err.message}`);
                reject(err);
            })
            .save(outputPath);
    });
}

/**
 * Get available templates
 */
function getTemplates() {
    return DEFAULT_TEMPLATES;
}

module.exports = {
    applyMetadata,
    getTemplates
};
